name: Upload Website to S3

on:
  push:
    branches:
      - main   # Runs the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@master
      with:
        fetch-depth: 0    # Fetch all history for all tags and branches

    # Step 2: Sync files to the S3 bucket
    - name: Sync files to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    - name: Get current version
        id: get_version
        run: |
          VERSION=$(cat VERSION.txt)
          echo "Current version is $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Create tag
        run: |
          git config user.name "Salah Eddine Ait Daoud"
          git config user.email "salahdaoud858@gmail.com"
          git tag -a "v${{ steps.get_version.outputs.VERSION }}" -m "Release v${{ steps.get_version.outputs.VERSION }}"
          git push origin "v${{ steps.get_version.outputs.VERSION }}"

