name: Upload Website to S3

on:
  push:
    branches:
      - main   # Runs the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Sync files to the S3 bucket
    - name: Sync files to S3
      uses: aws-actions/s3-sync-action@v2.3.0
      with:
        bucket: ${{ secrets.AWS_S3_BUCKET }}      # The S3 bucket name stored as a GitHub secret
        region: 'your-region'                     # Replace with your AWS region, e.g., 'us-east-1'
        source-dir: './'                          # Path to the files to sync (root of the repo)
        destination-dir: '/'                      # S3 bucket destination (root of the bucket)
        acl: 'public-read'                        # Makes the files publicly readable
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
